### PR TITLE
Fix scalafmt check context

### PR DESCRIPTION
**Pull request by mdedetrich**
Judging from another project I maintain I think this should be correct version?

### CODE REVIEW

**Comment by pjfanning** [comment]
Are we stuck in a Catch-22? We can't merge this because the status check won't pass. We can't commit to main branch directly - so we can't avoid the PR problem that way. We can't force push to main either.

**Comment by mdedetrich** [comment]
> Are we stuck in a Catch-22? We can't merge this because the status check won't pass. We can't commit to main branch directly - so we can't avoid the PR problem that way. We can't force push to main either.

Yes, I am creating an INFRA ticket to solve this.

**Review by pjfanning — APPROVED** [review]
lgtm - but we may need to get back to INFRA if this change doesn't work

**Comment by pjfanning** [comment]
I think .asf.yaml only has an effect if you commit the change in main branch.

**Pull request merged**
