### PR TITLE
Add scala steward

### PR DESCRIPTION
**Pull request by mdedetrich**
Add scala steward

### CODE REVIEW

**Review by pjfanning — APPROVED** [review]
lgtm - but INFRA only enable this one repro at a time, so you will need to contact them

**Comment by mdedetrich** [comment]
> lgtm - but INFRA only enable this one repro at a time, so you will need to contact them

Afaik I explicitly told them to enable all repo's, lets confirm when the runner gets executed.

**Comment by pjfanning** [comment]
> > lgtm - but INFRA only enable this one repro at a time, so you will need to contact them
> 
> Afaik I explicitly told them to enable all `incubator-pekko-*` repo's, lets confirm when the runner gets executed.

they told me this when I enabled scala steward for pekoo-connectors recently

**Comment by mdedetrich** [comment]
> they told me this when I enabled scala steward for pekoo-connectors recently

I see

**Comment by mdedetrich** [comment]
> they told me this when I enabled scala steward for pekoo-connectors recently

@pjfanning Do you have an example ticket for this?

**Pull request merged**
